### PR TITLE
Updating to work with Safari 11 and MacOS 10.13

### PR DESCRIPTION
**Pull request by zacharyozer**

### CODE REVIEW

**Comment by pratyushtewari** [comment]
Thanks @zacharyozer. I tested this change and works for me on 10.13.2

**Comment by zacharyozer** [comment]
Awesome! Do you wish to merge?

**Comment by pratyushtewari** [comment]
Will be nice if paperKup can merge this

**Comment by zacharyozer** [comment]
@PaperKup Can this be merged?

**Comment by vitormcsi** [comment]
Hi zacharyozer, in safari 11.0.3 I give the error "System Events devolveu o erro: Não é possível obter button \"Passwords\" of toolbar 1 of window 1 of application process \"Safari\"." number -1728 from button "Passwords" of toolbar 1 of window 1 of application process "Safari" how I fix? Thanks

**Comment by maciejrolecki** [comment]
I somehow did it and it worked but had to change some things
I didn't try anything else but it worked when the only window of safari being open is the setting window of safari, so open safari, open safari settings and close the web browsing window. 

After exporting the csv file from Chrome, delete the first line with the explanation and then delete the second of the 4 columns. In the 4 columns you should normally get:
- the base url
- the url but longer with more informations but I dont know what do you need them to apart from knowing nothing more ;) ( this one should be deleted)
- the username
- the password

`-- select the csv to import to iCloud keychain
set theFile to (choose file with prompt "Select the CSV file")

-- read csv file
set f to read theFile

-- split lines into records
set recs to paragraphs of f

-- open safari passwords screen, check it is unlocked, do not allow to proceed until it is unlocked or user clicks cancel 
tell application "System Events"
	tell application process "Safari"
		tell window "Passwords"
			repeat until (exists button "Add" of group 1 of group 1 of it)
				if not (exists button "Add" of group 1 of group 1 of it) then
					display dialog "To begin importing, unlock Safari passwords then click OK. Please do not use your computer until the process has completed." with title "CSV to iCloud Keychain"
				end if
			end repeat
		end tell
	end tell
end tell

-- getting values for each record
set vals to {}
set AppleScript's text item delimiters to ","
repeat with i from 1 to length of recs
	set end of vals to text items of (item i of recs)
	set kcURL to text item 1 of (item i of recs)
	set kcUsername to text item 2 of (item i of recs)
	set kcPassword to text item 3 of (item i of recs)
	
	-- write kcURL, kcUsername and kcPassword into text fields of safari passwords
	tell application "System Events"
		tell application process "Safari"
			set frontmost to true
			tell window 1
				
				click button "Add" of group 1 of group 1 of it
				-- write fields
				tell last row of table 1 of scroll area of group 1 of group 1 of it
					set value of text field 1 of it to kcURL
					keystroke tab
					set value of text field 2 of it to kcUsername
					keystroke tab
					set value of text field 3 of it to kcPassword
					keystroke return
				end tell
				
			end tell
		end tell
	end tell
end repeat
`

**Comment by racyroad** [comment]
Hello,

This script is not working with Safari 12. Returns an error: System Events got an error: Can’t set value of missing value to "Akita.com". How can this be fixed?

**Comment by danielhawkett** [comment]
Doesn't appear to be working on Safari 12.0 running MacOS Mojave 10.14. Any way to get a fix?

**Pull request merged**
